#pragma once

// from glfw3.h

#define VUSE_MOUSE_BUTTON_1         0
#define VUSE_MOUSE_BUTTON_2         1
#define VUSE_MOUSE_BUTTON_3         2
#define VUSE_MOUSE_BUTTON_4         3
#define VUSE_MOUSE_BUTTON_5         4
#define VUSE_MOUSE_BUTTON_6         5
#define VUSE_MOUSE_BUTTON_7         6
#define VUSE_MOUSE_BUTTON_8         7
#define VUSE_MOUSE_BUTTON_LAST      VUSE_MOUSE_BUTTON_8
#define VUSE_MOUSE_BUTTON_LEFT      VUSE_MOUSE_BUTTON_1
#define VUSE_MOUSE_BUTTON_RIGHT     VUSE_MOUSE_BUTTON_2
#define VUSE_MOUSE_BUTTON_MIDDLE    VUSE_MOUSE_BUTTON_3